services:
  db:
    build:
      context: ./docker/db
    environment:
      APP: ${APP}
      DATABASE: ${DATABASE}
      OWNER: ${OWNER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    external: false
